name: Crea ZIP dai contenuti

on:
  workflow_dispatch:
    inputs:
      content1:
        description: "Contenuto di Manifest.xml"
        required: true
      content2:
        description: "Contenuto di PackageHeader.xml"
        required: true
      content3:
        description: "Contenuto di Al1PackingPreparationEntity.xml"
        required: true
      zipname:
        description: "Nome dello zip finale (senza estensione)"
        required: true
        default: "miozip"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup artifacts
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: context.workflow,
              per_page: 5,
            });
            for (const run of runs.data.workflow_runs) {
              const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner,
                repo,
                run_id: run.id,
              });
              for (const art of artifacts.data.artifacts) {
                console.log(`Deleting artifact: ${art.id} (${art.name})`);
                await github.rest.actions.deleteArtifact({
                  owner,
                  repo,
                  artifact_id: art.id,
                });
              }
            }

  build:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Manifest.xml
        run: |
          echo "${{ github.event.inputs.content1 }}" > Manifest.xml

      - name: Create PackageHeader.xml
        run: |
          echo "${{ github.event.inputs.content2 }}" > PackageHeader.xml

      - name: Create Al1PackingPreparationEntity.xml
        run: |
          echo "${{ github.event.inputs.content3 }}" > Al1PackingPreparationEntity.xml

      - name: Create zip
        run: |
          echo "=== ls prima di zip ==="
          ls -lh
          echo
          zip -j "${{ github.event.inputs.zipname }}.zip" \
                 Manifest.xml \
                 PackageHeader.xml \
                 Al1PackingPreparationEntity.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.zipname }}
          path: ${{ github.event.inputs.zipname }}.zip
