name: Crea ZIP dai contenuti

on:
  workflow_dispatch:
    inputs:
      content1:
        description: "Contenuto di Manifest.xml"
        required: true
      content2:
        description: "Contenuto di PackageHeader.xml"
        required: true
      content3:
        description: "Contenuto di Al1PackingPreparationEntity.xml"
        required: true
      zipname:
        description: "Nome dello zip finale (senza estensione)"
        required: true
        default: "miozip"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup artifacts
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: context.workflow,
              per_page: 5,
            })
