name: Zip 3 Files API

on:
  workflow_dispatch:
    inputs:
      file1:
        description: 'URL diretto del primo file'
        required: true
      file2:
        description: 'URL diretto del secondo file'
        required: true
      file3:
        description: 'URL diretto del terzo file'
        required: true
      zipname:
        description: 'Nome file zip (senza estensione)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica file1
        run: wget -q --content-disposition "${{ github.event.inputs.file1 }}" -O file1

      - name: Scarica file2
        run: wget -q --content-disposition "${{ github.event.inputs.file2 }}" -O file2

      - name: Scarica file3
        run: wget -q --content-disposition "${{ github.event.inputs.file3 }}" -O file3

      - name: Verifica contenuto
        run: ls -lh

      - name: Crea zip
        run: zip -j ${{ github.event.inputs.zipname }}.zip file1 file2 file3

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.zipname }}
          path: ${{ github.event.inputs.zipname }}.zip
