name: Zip 3 Files API

on:
  workflow_dispatch:
    inputs:
      file1:
        description: 'URL diretto del primo file'
        required: true
      file2:
        description: 'URL diretto del secondo file'
        required: true
      file3:
        description: 'URL diretto del terzo file'
        required: true
      zipname:
        description: 'Nome file zip (senza estensione)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica file1
        run: curl -f -L "${{ github.event.inputs.file1 }}" -o file1.bin

      - name: Scarica file2
        run: curl -f -L "${{ github.event.inputs.file2 }}" -o file2.bin

      - name: Scarica file3
        run: curl -f -L "${{ github.event.inputs.file3 }}" -o file3.bin

      - name: Verifica contenuto
        run: ls -lh && file file1.bin file2.bin file3.bin

      - name: Crea zip
        run: zip -r ${{ github.event.inputs.zipname }}.zip file1.bin file2.bin file3.bin

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.zipname }}
          path: ${{ github.event.inputs.zipname }}.zip
