name: Zip from content

on:
  workflow_dispatch:
    inputs:
      content1:
        description: 'Contenuto del file uno'
        required: true
      name1:
        description: 'Nome del file uno con estensione (es: file1.txt)'
        required: true
      content2:
        description: 'Contenuto del file due'
        required: true
      name2:
        description: 'Nome del file due'
        required: true
      content3:
        description: 'Contenuto del file tre'
        required: true
      name3:
        description: 'Nome del file tre'
        required: true
      zipname:
        description: 'Nome del file zip generato (senza .zip)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create file1
        run: echo "${{ github.event.inputs.content1 }}" > "${{ github.event.inputs.name1 }}"

      - name: Create file2
        run: echo "${{ github.event.inputs.content2 }}" > "${{ github.event.inputs.name2 }}"

      - name: Create file3
        run: echo "${{ github.event.inputs.content3 }}" > "${{ github.event.inputs.name3 }}"

      - name: Verifica contenuto
        run: ls -lh && cat "${{ github.event.inputs.name1 }}" || true

      - name: Crea zip piatto
        run: zip -j "${{ github.event.inputs.zipname }}.zip" \
               "${{ github.event.inputs.name1 }}" \
               "${{ github.event.inputs.name2 }}" \
               "${{ github.event.inputs.name3 }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.zipname }}
          path: ${{ github.event.inputs.zipname }}.zip
