name: Zip 3 Files API

on:
  workflow_dispatch:
    inputs:
      content1:
        description: "Contenuto del primo file"
        required: true
      content2:
        description: "Contenuto del secondo file"
        required: true
      content3:
        description: "Contenuto del terzo file"
        required: true
      zipname:
        description: "Nome dello zip finale (senza estensione)"
        required: true
        default: "miozip"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete old artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching artifacts..."
          artifacts=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[].id')
          for artifact_id in $artifacts; do
            echo "Deleting artifact ID: $artifact_id"
            gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$artifact_id || true
          done

  build:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare output folder
        run: mkdir output

      - name: Create Manifest.xml
        run: |
          echo "${{ github.event.inputs.content1 }}" > output/Manifest.xml

      - name: Create PackageHeader.xml
        run: |
          echo "${{ github.event.inputs.content2 }}" > output/PackageHeader.xml

      - name: Create Al1PackingPreparationEntity.xml
        run: |
          echo "${{ github.event.inputs.content3 }}" > output/Al1PackingPreparationEntity.xml

      - name: Debug files
        run: |
          ls -lh output
          file output/* || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.zipname }}
          path: output/
