name: Zip from content

on:
  workflow_dispatch:
    inputs:
      content1:
        description: 'Contenuto file uno'
        required: true
      name1:
        description: 'Nome file uno (es: Manifest.xml)'
        required: true
      content2:
        description: 'Contenuto file due'
        required: true
      name2:
        description: 'Nome file due (es: PackageHeader.xml)'
        required: true
      content3:
        description: 'Contenuto file tre'
        required: true
      name3:
        description: 'Nome file tre (es: Al1PackingPreparationEntity.xml)'
        required: true
      zipname:
        description: 'Nome dello zip (senza estensione)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create file1
        run: |
          cat <<'EOF' > "${{ github.event.inputs.name1 }}"
          ${{ github.event.inputs.content1 }}
          EOF

      - name: Create file2
        run: |
          cat <<'EOF' > "${{ github.event.inputs.name2 }}"
          ${{ github.event.inputs.content2 }}
          EOF

      - name: Create file3
        run: |
          cat <<'EOF' > "${{ github.event.inputs.name3 }}"
          ${{ github.event.inputs.content3 }}
          EOF

      - name: Crea zip
        run: zip -j "${{ github.event.inputs.zipname }}.zip" \
                  "${{ github.event.inputs.name1 }}" \
                  "${{ github.event.inputs.name2 }}" \
                  "${{ github.event.inputs.name3 }}"

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.inputs.zipname }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
