name: Cleanup + Zip from content

on:
  workflow_dispatch:
    inputs:
      content1:
        description: 'Contenuto file uno'
        required: true
      name1:
        description: 'Nome file uno (es: Manifest.xml)'
        required: true
      content2:
        description: 'Contenuto file due'
        required: true
      name2:
        description: 'Nome file due (es: PackageHeader.xml)'
        required: true
      content3:
        description: 'Contenuto file tre'
        required: true
      name3:
        description: 'Nome file tre (es: Al1PackingPreparationEntity.xml)'
        required: true
      zipname:
        description: 'Nome dello zip (senza estensione)'
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all artifacts
        run: |
          echo "Fetching artifacts..."
          artifacts=$(gh api repos/${GITHUB_REPOSITORY}/actions/artifacts --paginate -q '.artifacts[].id')
          if [ -z "$artifacts" ]; then
            echo "✅ Nessun artifact trovato"
          else
            for id in $artifacts; do
              echo "Deleting artifact ID: $id"
              gh api repos/${GITHUB_REPOSITORY}/actions/artifacts/$id -X DELETE
            done
            echo "✅ Tutti gli artifacts sono stati cancellati"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Create file1
        run: |
          cat <<'EOF' > "${{ github.event.inputs.name1 }}"
          ${{ github.event.inputs.content1 }}
          EOF

      - name: Create file2
        run: |
          cat <<'EOF' > "${{ github.event.inputs.name2 }}"
          ${{ github.event.inputs.content2 }}
          EOF

      - name: Create file3
        run: |
          cat <<'EOF' > "${{ github.event.inputs.name3 }}"
          ${{ github.event.inputs.content3 }}
          EOF

      - name: Crea zip
        run: zip -j "${{ github.event.inputs.zipname }}.zip" \
                  "${{ github.event.inputs.name1 }}" \
                  "${{ github.event.inputs.name2 }}" \
                  "${{ github.event.inputs.name3 }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.zipname }}
          path: ${{ github.event.inputs.zipname }}.zip
